version: '3.7'

services:
  linkanizer_web:
    container_name: linkanizer_web
    build: .
    entrypoint: /code/django-entrypoint.sh
    ports:
      - 19360:8000
    environment:
      DJANGO_SETTINGS_MODULE: "api.settings.production"
    volumes:
      - ${PWD}/prod.sqlite3:/code/prod.sqlite3
  linkanizer_worker:
    container_name: linkanizer_worker
    build: .
    entrypoint: /code/worker-entrypoint.sh
    environment:
      DJANGO_SETTINGS_MODULE: "api.settings.production"
    volumes:
      - ${PWD}/prod.sqlite3:/code/prod.sqlite3
  linkanizer_redis:
    container_name: linkanizer_redis
    image: redis:alpine
    restart: always
