version: '3.7'

services:
  linkanizer_web:
    container_name: linkanizer_web
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    ports:
      - 19360:8000
    environment:
      DJANGO_SETTINGS_MODULE: "api.settings.production"
    volumes:
      - ${PWD}/prod.sqlite3:/code/prod.sqlite3
  linkanizer_redis:
    container_name: linkanizer_redis
    image: redis:alpine
    restart: always
