# Generated by Django 3.0 on 2020-01-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkanizer", "0002_auto_20200103_2304"),
    ]

    operations = [
        migrations.AddField(
            model_name="link", name="description", field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="link", name="imageUrl", field=models.URLField(default=""),
        ),
    ]
