# Generated by Django 3.0 on 2020-01-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkanizer", "0003_auto_20200104_1609"),
    ]

    operations = [
        migrations.AddField(
            model_name="link", name="visits", field=models.IntegerField(default=0),
        ),
    ]
